---
title: npm-registry-proxy
---
erDiagram
    User ||..o{ Usage: "is associated with"
    User ||..o{ Request: "makes/is made by"
    Request ||..|| Response: "is fulfilled by/fulfills"
    User {
        UUID id PK
        string username "NOT NULL UNIQUE"
        string api_key "NOT NULL UNIQUE"
    }
    Usage {
        UUID id PK
        string date "NOT NULL"
        integer count "NOT NULL"
        UUID user_id FK
    }
    Request {
        UUID id PK
        string time "NOT NULL"
        jsonb headers
        UUID response_id  FK
        UUID user_id FK
    }
    Response {
        UUID id PK
        string time "NOT NULL"
        jsonb headers
        jsonb body
        UUID request_id FK "NOT NULL"
    }

